-- SQLite
CREATE TABLE reservations (
    "Hostaway reservation ID" INTEGER,
    "Guest name" TEXT,
    "Check-in date" TEXT,
    "Check-out date" TEXT,
    "Channel" TEXT,
    "Total price" REAL,
    "Currency" TEXT,
    "Airbnb expected payout amount" REAL,
    "Number of guests" INTEGER,
    "Number of nights" INTEGER,
    "Status" TEXT,
    "Reservation date" TEXT,
    "Listing" TEXT,
    "Channel commission" REAL,
    "Guest location" TEXT,
    "Guest city" TEXT,
    "Guest country" TEXT,
    "Cleaning fee" REAL,
    "Channel Unit ID" INTEGER,
    "Airbnb total paid amount" REAL,
    "Payment status" TEXT,
    "Total paid" REAL,
    "Remaining balance" REAL,
    "ListingMap ID" INTEGER,
    "Listing name" TEXT
);
